# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoda_app', '0002_auto_20160608_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
