# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoda_app', '0005_auto_20160608_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
